### ISSUE TITLE
sort_slopes does not work

### ISSUE THREAD

**Issue by 0avasns** [dustinfife/flexplavaan#10]
```
> residual_plots(m1DfitG1, max_val = .01)  # works fine
> visualize(m1DfitG1) # works fine
> implied_measurement(m1DfitG1, latent="Da", limit=10) # works fine
[[1]]

> implied_measurement(m1DfitG1, latent="Da", limit=10, sort_slopes=T) # the default value, same as above
[[1]]

> implied_measurement(m1DfitG1, latent="Da", limit=10, sort_slopes=F) # fails
Error: $ operator is invalid for atomic vectors
> 
```

**Comment by dustinfife** [comment]
I appreciate you finding all my bugs :)  I'll see if I can get to this tomorrow.

**Comment by 0avasns** [comment]
No rush from my side :-)
I really appreciate your offering this tool and I am excited to try it out, that's all.
Let me know if I can be of further help (like, provide data/scripts or look into parts of code)

**Comment by dustinfife** [comment]
I can't reproduce this error. It might have been fixed on the development branch. Try installing that:

`devtools::install_github("dustinfife/flexplavaan", ref="development")`

**Comment by 0avasns** [comment]
I confirm that `sort_slopes=F` works fine with the latest development version. Thank you!
