### ISSUE TITLE
Problems installing flexplavaan

### ISSUE THREAD

**Issue by mkshirley87** [dustinfife/flexplavaan#6]
Hi there, 
I'm trying to use flexplavaan for the first time, to make a structural plot, but I'm having problems installing. 

It's throwing up the below error - any ideas? 

thank you!
Meghan

ERROR: dependency ‘flexplot’ is not available for package ‘flexplavaan’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/flexplavaan’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/g4/8gv6dgl150l8hpj3gpn00lvc0000gn/T//RtmpOLuX1C/filea9591ac0566d/flexplavaan_0.1.8.tar.gz’ had non-zero exit status

**Comment by dustinfife** [comment]
That should be an easy fix. You need to install flexplot, which isn't on CRAN. So you have to install that from github:

```
install.packages("devtools") # install devtools if you don't have it already
devtools::install_github('dustinfife/flexplot')
```

**Comment by mkshirley87** [comment]
Great, seems to have worked- thanks!
